# Generated by Django 5.0.6 on 2024-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='householditem',
            name='add_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
